# Generated by Django 6.1 on 2026-08-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('STOCK_ADD', 'Stock added'), ('DAMAGE_EXPIRE_REMOVAL', 'Damage or expiry removal'), ('PRICE_UPDATE', 'Price update'), ('MANUAL_CORRECTION', 'Manual correction')], max_length=30)),
                ('quantity_changed', models.IntegerField()),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
