# Generated by Django 6.1 on 2026-09-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mark_staff_as_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(default='MediFlow Pharmacy', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('receipt_footer', models.CharField(default='Thank you for choosing MediFlow Pharmacy.', max_length=255)),
                ('auto_print_receipt', models.BooleanField(default=True)),
                ('low_stock_notifications', models.BooleanField(default=True)),
                ('expiry_alert_days', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
