# Generated by Django 6.1 on 2026-08-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('pack_size', models.CharField(blank=True, max_length=255)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source_link', models.URLField(blank=True, max_length=500)),
                ('letter', models.CharField(blank=True, db_index=True, max_length=10)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'company', 'pack_size'), name='unique_reference_medicine')],
            },
        ),
    ]
